# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
skipsdist = True
skip_missing_interpreters = True
envlist = lint, format

[vars]
all_paths = {[vars]tests_path} {[vars]python_worker_path}
tests_path = {toxinidir}/tests/
python_worker_path = {toxinidir}/worker_python/

[testenv]
allowlist_externals =
    /bin/bash
    uv

pass_env =
    PYTHONPATH
set_env =
    PYTHONPATH = {toxinidir}
    PYTHONBREAKPOINT = ipdb.set_trace
    PY_COLORS = 1

[testenv:lint]
description = Lint python code
deps =
    .[lint]
allowlist_externals =
    {[testenv]allowlist_externals}
    find
commands =
    uv run codespell {[vars]all_paths}
    uv run ruff check {[vars]all_paths}
    uv run ruff format --check --diff {[vars]all_paths}
    find {[vars]all_paths} -type f \( -name "*.sh" -o -name "*.bash" \) -exec uv run shellcheck --color=always \{\} +

[testenv:format]
description = Apply coding style standards to code
deps =
    .[format]
commands =
    uv run ruff check --fix {[vars]all_paths}
    uv run ruff format {[vars]all_paths}

[testenv:uats-namespace-isolation]
description = Execute namespace isolation UATs
deps =
    .[uats]
commands =
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}test_namespace_isolation.py

[testenv:uats-ingress]
description = Execute ingress UATs
deps =
    .[uats]
commands =
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}test_ingress.py

[testenv:uats-cos]
description = Execute COS UATs
deps =
    .[uats]
commands =
    pytest -v --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}test_cos.py
