name: UAT tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      track:
        description: 'Charm channel track'
        required: false
        default: '1.23'
        type: string
      risk:
        description: 'Charm channel risk to test against'
        required: true
        default: 'edge'
        type: choice
        options:
          - edge
          - beta
          - candidate
          - stable

jobs:
  uats:
    name: Run UATs
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        uat:
          - uats-namespace-isolation
          - uats-ingress
          - uats-cos
      fail-fast: false
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.uat }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' }}

    steps:
      - name: Maximize GH runner disk
        uses: jlumbroso/free-disk-space@v1.3.1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up operator environment
        run: |
          set -e

          goss_base_url="https://github.com/goss-org/goss/releases/latest/download"
          curl -L ${goss_base_url}/goss-linux-amd64 -o /usr/local/bin/goss
          chmod +rx /usr/local/bin/goss

          sudo apt-get purge $(dpkg -l | grep -i docker | awk '{print $2}')
          sudo apt-get purge containerd.io
          sudo rm -r /run/containerd

          sudo snap install concierge --classic

          sudo snap install just --classic

          sudo -E concierge prepare -p k8s --extra-snaps=astral-uv

          sudo k8s set load-balancer.l2-mode=true load-balancer.cidrs=10.2.0.0/24
          sudo k8s enable ingress load-balancer

          sudo k8s kubectl config view --raw > ~/.kube/config

          uv tool install tox

          just install-nginx-controller

      - name: Install docker (after k8s bootstrapped)
        run: |
          sudo snap install docker
          sudo snap start docker

      - name: Deploy Temporal models
        run: just deploy-temporal ${{ inputs.track || '1.23' }} ${{ inputs.risk || 'edge' }}

      - name: Execute UATs
        run: just ${{ matrix.uat }}

      - name: Get system state (if failure)
        if: failure()
        run: just get-system-state
